apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1

  selector:
    matchLabels:
      app: prometheus

  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        # Imagen pública de referencia — reemplaza con tu imagen ECR si la tienes:
        # image: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/prometheus-healthtrack:1.0.0
        image: prom/prometheus:latest

        ports:
        - containerPort: 9090

        env:
        - name: APP_ENV
          value: "production"
