FROM prom/prometheus:latest

LABEL maintainer="Rodrigo Aguilar G. <r.aguilarg@profesor.duoc.cl>"
LABEL version="1.0.0"
LABEL description="Prometheus para monitoreo clínico - Caso HealthTrack INY1105"

VOLUME ["/prometheus", "/etc/prometheus"]

EXPOSE 9090
