apiVersion: v1
kind: Service
metadata:
  # TODO: Define el nombre del Service
  name: ???
  namespace: monitoring
spec:
  selector:
    # TODO: Debe coincidir con el label del Deployment
    app: ???
  ports:
  - protocol: TCP
    # TODO: Puerto del Service (interno al cluster)
    port: ???
    # TODO: Puerto del contenedor (debe coincidir con containerPort del Deployment)
    targetPort: ???
  # TODO: Tipo de Service: ClusterIP | NodePort | LoadBalancer
  type: ???
