apiVersion: v1
kind: Service
metadata:
  name: prometheus-v2
  namespace: monitoring
spec:
  selector:
    app: prometheus-v2
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  type: ClusterIP
